# Generated by Django 4.0.4 on 2022-04-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('vocation', models.CharField(choices=[('KNIGHT', 'Knight'), ('ELITE_KNIGHT', 'Elite Knight'), ('PALADIN', 'Paladin'), ('ROYAL_PALADIN', 'Royal Paladin'), ('SORCERER', 'Sorcerer'), ('MASTER_SORCERER', 'Master Sorcerer'), ('DRUID', 'Druid'), ('ELDER_DRUID', 'Elder Druid'), ('NONE', 'None')], default='None', max_length=15)),
                ('level', models.PositiveSmallIntegerField()),
                ('achievement_points', models.PositiveSmallIntegerField()),
                ('world', models.CharField(max_length=30)),
            ],
        ),
    ]
