# Generated by Django 4.0.4 on 2022-04-20 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Character',
            new_name='Test_Character',
        ),
    ]
