# Generated by Django 4.0.4 on 2022-04-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_rename_character_test_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_character',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
